import { existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { createInterface } from 'node:readline/promises';
import { parseArgs } from 'node:util';
import { parseDocument } from 'yaml';
import {
  buildScripts,
  CONTENT_MANIFEST,
  CONTENT_TYPES,
  EXAMPLE_PLUGIN_PREFIX,
  parseContentList,
  ROOT_SKILL_EXAMPLES,
  selectedTypes,
  STARTER_SKILL,
  type ContentManifest,
  type SelectableContent,
} from './content.ts';
import { renderTable, replaceTable } from './generate-readme-table.ts';
import { findBrokenRelativeLinks } from './init/links.ts';
import { applySections } from './init/sections.ts';
import { listPluginNames, MARKETPLACE_FILE, PLUGINS_DIR, SKILLS_DIR } from './lib/layout.ts';
import { runInherited } from './lib/run.ts';
import { marketplaceSchema, packageJsonSchema, pluginManifestSchema, readJson } from './lib/schemas.ts';

/** The values the template carries, replaced in the generated repository. */
export const TEMPLATE_NAME = 'agent-marketplace-template';
export const TEMPLATE_ORG = 'ExaDev';
export const TEMPLATE_OWNER = 'ExaDev';

/** SPDX-style identifier npm and Claude Code accept for a package that grants no licence. */
const UNLICENSED = 'UNLICENSED';

export type Licence = 'MIT' | 'proprietary';
export type Examples = 'keep' | 'none';

export interface InitOptions {
  /** The repository to transform, in place. */
  dir: string;
  /** Marketplace and package name; lower-case words joined by hyphens, which is what Claude Code requires of a marketplace name. */
  name: string;
  /** Display name of the owner, written to the marketplace owner, plugin authors and the licence. */
  owner: string;
  /** GitHub organisation or user, written into repository URLs. */
  org: string;
  content: readonly SelectableContent[];
  licence: Licence;
  examples: Examples;
  /** Copyright year, injected so the result does not depend on the clock. */
  year: number;
}

const NAME_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const SKIPPED_DIRECTORIES = new Set(['node_modules', '.git']);
/** Not text the placeholders apply to: the lockfile is regenerated by the install that follows. */
const SKIPPED_FILES = new Set(['pnpm-lock.yaml']);

/** Applies the options to the repository at `options.dir`. Changes files only; installing and validating are separate steps. */
export function applyInit(options: InitOptions, manifest: ContentManifest = CONTENT_MANIFEST): void {
  if (!NAME_PATTERN.test(options.name)) throw new Error(`--name "${options.name}" must be lower-case words joined by hyphens`);
  const { dir } = options;
  const selected = selectedTypes(options.content);
  const hasClaude = selected.has('claude');

  if (!hasClaude && options.examples === 'keep') relocateExampleSkills(dir);
  for (const type of CONTENT_TYPES) {
    if (!selected.has(type)) removeOwned(dir, manifest.modules[type].paths);
  }
  removeOwned(dir, manifest.templatePaths);

  if (options.examples === 'none') {
    if (hasClaude) removeExamplePlugins(dir);
    else writeStarterSkill(dir);
  }

  writePackageJson(dir, options, manifest);
  writeWorkspaceYaml(dir, selected, manifest);
  if (hasClaude) writePluginMetadata(dir, options);

  forEachTextFile(dir, (path, text) => {
    const sectioned = applySections(text, selected, relative(dir, path));
    const replaced = sectioned
      .replaceAll(`${TEMPLATE_ORG}/${TEMPLATE_NAME}`, `${options.org}/${options.name}`)
      .replaceAll(TEMPLATE_NAME, options.name);
    if (replaced !== text) writeFileSync(path, replaced);
  });

  writeLicence(dir, options);
  const readmePath = join(dir, 'README.md');
  writeFileSync(readmePath, replaceTable(readFileSync(readmePath, 'utf8'), renderTable(dir)));

  const broken = findBrokenRelativeLinks(dir);
  if (broken.length > 0) throw new Error(`the generated repository has broken relative links; wrap their sources in content markers:\n${broken.join('\n')}`);
}

function removeOwned(dir: string, paths: readonly string[]): void {
  for (const path of paths) {
    const full = join(dir, path);
    if (!existsSync(full)) throw new Error(`the content manifest owns ${path}, which does not exist in ${dir}`);
    rmSync(full, { recursive: true });
  }
}

/** Moves the example plugin's skills (and the shared files they reach with relative links) to the repository root. */
function relocateExampleSkills(dir: string): void {
  const source = join(dir, PLUGINS_DIR, ROOT_SKILL_EXAMPLES.plugin);
  for (const move of ROOT_SKILL_EXAMPLES.moves) {
    const target = join(dir, move);
    if (existsSync(target)) throw new Error(`cannot move ${relative(dir, join(source, move))}: ${move} already exists`);
    renameSync(join(source, move), target);
  }
}

function removeExamplePlugins(dir: string): void {
  const removed = listPluginNames(dir).filter((name) => name.startsWith(EXAMPLE_PLUGIN_PREFIX));
  for (const name of removed) rmSync(join(dir, PLUGINS_DIR, name), { recursive: true });
  const path = join(dir, MARKETPLACE_FILE);
  const marketplace = readJson(path, marketplaceSchema);
  writeJson(path, { ...marketplace, plugins: marketplace.plugins.filter((entry) => !removed.includes(entry.name)) });
}

function writeStarterSkill(dir: string): void {
  const skillDir = join(dir, SKILLS_DIR, STARTER_SKILL);
  mkdirSync(skillDir, { recursive: true });
  writeFileSync(
    join(skillDir, 'SKILL.md'),
    `---\nname: ${STARTER_SKILL}\ndescription: Placeholder skill that shows the file shape. Replace it with a skill that says what it does and when to use it.\n---\n\nReplace this body with the instructions the agent follows when the skill applies.\n`,
  );
}

function writePackageJson(dir: string, options: InitOptions, manifest: ContentManifest): void {
  const path = join(dir, 'package.json');
  const pkg = readJson(path, packageJsonSchema);
  const selected = selectedTypes(options.content);
  const dropped = new Set(CONTENT_TYPES.filter((type) => !selected.has(type)).flatMap((type) => manifest.modules[type].devDependencies));
  const devDependencies = Object.fromEntries(Object.entries(pkg.devDependencies ?? {}).filter(([name]) => !dropped.has(name)));
  writeJson(path, { ...pkg, name: options.name, scripts: buildScripts(selected, false), devDependencies });
}

function writeWorkspaceYaml(dir: string, selected: ReturnType<typeof selectedTypes>, manifest: ContentManifest): void {
  const path = join(dir, 'pnpm-workspace.yaml');
  const document = parseDocument(readFileSync(path, 'utf8'));
  for (const type of CONTENT_TYPES) {
    if (selected.has(type)) continue;
    for (const key of manifest.modules[type].workspaceKeys) document.delete(key);
  }
  writeFileSync(path, String(document));
}

/** Sets the owner on the marketplace and each remaining plugin, and the licence field when the licence is not MIT. */
function writePluginMetadata(dir: string, options: InitOptions): void {
  const marketplacePath = join(dir, MARKETPLACE_FILE);
  const marketplace = readJson(marketplacePath, marketplaceSchema);
  writeJson(marketplacePath, { ...marketplace, name: options.name, owner: { ...marketplace.owner, name: options.owner } });
  for (const name of listPluginNames(dir)) {
    const path = join(dir, PLUGINS_DIR, name, '.claude-plugin', 'plugin.json');
    const manifest = readJson(path, pluginManifestSchema);
    const author = manifest.author === undefined ? {} : { author: { ...manifest.author, name: options.owner } };
    const license = options.licence === 'MIT' ? {} : { license: UNLICENSED };
    writeJson(path, { ...manifest, ...author, ...license });
  }
}

function writeLicence(dir: string, options: InitOptions): void {
  const path = join(dir, 'LICENSE');
  if (options.licence === 'proprietary') {
    writeFileSync(
      path,
      `Copyright (c) ${String(options.year)} ${options.owner}. All rights reserved.\n\nThis repository and its contents are proprietary. No licence is granted to use, copy, modify or distribute them without the written permission of the copyright holder.\n`,
    );
    return;
  }
  const text = readFileSync(path, 'utf8');
  const updated = text.replace(/^Copyright \(c\) \d{4} .*$/m, `Copyright (c) ${String(options.year)} ${options.owner}`);
  if (updated === text && !text.includes(`Copyright (c) ${String(options.year)} ${options.owner}`)) throw new Error('LICENSE has no copyright line to update');
  writeFileSync(path, updated);
}

function writeJson(path: string, value: unknown): void {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

/** Visits every regular text file outside node_modules and .git. Symbolic links are left alone (they point at files visited in their own right) and a file containing a NUL byte is binary and skipped. */
function forEachTextFile(dir: string, visit: (path: string, text: string) => void): void {
  for (const entry of readdirSync(dir)) {
    if (SKIPPED_DIRECTORIES.has(entry) || SKIPPED_FILES.has(entry)) continue;
    const full = join(dir, entry);
    const stat = lstatSync(full);
    if (stat.isSymbolicLink()) continue;
    if (stat.isDirectory()) {
      forEachTextFile(full, visit);
      continue;
    }
    const buffer = readFileSync(full);
    if (buffer.includes(0)) continue;
    visit(full, buffer.toString('utf8'));
  }
}

// Command line -----------------------------------------------------------------------------------------------

const USAGE = `Usage: pnpm run init [options]

  --content <list>    skills, claude or all, comma-separated (default all)
  --name <name>       marketplace and package name (lower-case, hyphenated)
  --owner <name>      owner display name for the marketplace, plugin authors and licence
  --org <name>        GitHub organisation or user for repository URLs (default: the owner)
  --licence <kind>    MIT or proprietary (default MIT)
  --examples <kind>   keep or none (default keep)
  --dir <path>        repository to transform (default: the current directory)
  --yes               never prompt; a missing --name or --owner is an error
  --no-validate       skip the install and validation that normally follow`;

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: {
      content: { type: 'string', default: 'all' },
      name: { type: 'string' },
      owner: { type: 'string' },
      org: { type: 'string' },
      licence: { type: 'string', default: 'MIT' },
      examples: { type: 'string', default: 'keep' },
      dir: { type: 'string', default: process.cwd() },
      yes: { type: 'boolean', default: false },
      'no-validate': { type: 'boolean', default: false },
      help: { type: 'boolean', default: false },
    },
  });
  if (values.help) {
    console.log(USAGE);
    return;
  }
  const dir = resolve(values.dir);
  const name = values.name ?? (await ask('Marketplace name', values.yes, '--name'));
  const owner = values.owner ?? (await ask('Owner (display name)', values.yes, '--owner'));
  applyInit({
    dir,
    name,
    owner,
    org: values.org ?? owner,
    content: parseContentList(values.content),
    licence: parseChoice(values.licence, ['MIT', 'proprietary'], '--licence'),
    examples: parseChoice(values.examples, ['keep', 'none'], '--examples'),
    year: new Date().getFullYear(),
  });
  if (values['no-validate']) return;
  runInherited('pnpm', ['install', '--no-frozen-lockfile'], dir);
  runInherited('pnpm', ['run', 'validate'], dir);
}

function parseChoice<T extends string>(value: string, valid: readonly T[], flag: string): T {
  const match = valid.find((candidate) => candidate === value);
  if (match === undefined) throw new Error(`${flag} must be one of ${valid.join(', ')}, not "${value}"`);
  return match;
}

async function ask(question: string, nonInteractive: boolean, flag: string): Promise<string> {
  if (nonInteractive || !process.stdin.isTTY) throw new Error(`${flag} is required without a prompt`);
  const readline = createInterface({ input: process.stdin, output: process.stdout });
  try {
    const answer = (await readline.question(`${question}: `)).trim();
    if (answer === '') throw new Error(`${flag} cannot be empty`);
    return answer;
  } finally {
    readline.close();
  }
}

if (import.meta.main) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
